server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/test_db?serverTimezone=GMT
    username: xxxx
    password: xxxx
  thymeleaf:
    cache: false


# mybatis配置
mybatis:
  type-aliases-package: com.maizi.fund.mapper
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
